# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ProductboardCli < Formula
  desc "Read-only CLI tool for ProductBoard API"
  homepage "https://github.com/tabesto/productboard-cli"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Tabesto/productboard-cli/releases/download/v0.4.0/productboard-cli_0.4.0_darwin_amd64.tar.gz"
      sha256 "141127b2918c79f482847237113d810e02c5971c94815857646b35fa7645f984"

      define_method(:install) do
        bin.install "pboard"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Tabesto/productboard-cli/releases/download/v0.4.0/productboard-cli_0.4.0_darwin_arm64.tar.gz"
      sha256 "63764c6df6092150f4ee558430b555448f9e95deeed97348bda7c1543a5381ab"

      define_method(:install) do
        bin.install "pboard"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Tabesto/productboard-cli/releases/download/v0.4.0/productboard-cli_0.4.0_linux_amd64.tar.gz"
      sha256 "e09303461db452c661391f12c7a09fed61c5b1f474700902e1d5fb614527f5ce"
      define_method(:install) do
        bin.install "pboard"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Tabesto/productboard-cli/releases/download/v0.4.0/productboard-cli_0.4.0_linux_arm64.tar.gz"
      sha256 "077ddbd9faacbe557d314da5cacb30c60fcfb223e4ba295e92e08754310105e7"
      define_method(:install) do
        bin.install "pboard"
      end
    end
  end

  test do
    system "#{bin}/pboard", "--version"
  end
end
