# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ProductboardCli < Formula
  desc "Read-only CLI tool for ProductBoard API"
  homepage "https://github.com/tabesto/productboard-cli"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Tabesto/productboard-cli/releases/download/v0.3.0/productboard-cli_0.3.0_darwin_amd64.tar.gz"
      sha256 "1366ded04c089af8dfa0e7f09abc690b3c7999d8ed3029df69914a7de1389567"

      define_method(:install) do
        bin.install "pboard"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Tabesto/productboard-cli/releases/download/v0.3.0/productboard-cli_0.3.0_darwin_arm64.tar.gz"
      sha256 "2b279e3f6694e61ecaaffd03b50d36c8f5157f46e5f5b5a5c595534fe18a244f"

      define_method(:install) do
        bin.install "pboard"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Tabesto/productboard-cli/releases/download/v0.3.0/productboard-cli_0.3.0_linux_amd64.tar.gz"
      sha256 "a576e36e0b89b590a6f95c155d48aba5c79fcce094034ed94c59831794cd89c6"
      define_method(:install) do
        bin.install "pboard"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Tabesto/productboard-cli/releases/download/v0.3.0/productboard-cli_0.3.0_linux_arm64.tar.gz"
      sha256 "c3122d3cc741d53f03aff16fe3fa33f6793453c0baccd730fbfb5bd36e82d6ac"
      define_method(:install) do
        bin.install "pboard"
      end
    end
  end

  test do
    system "#{bin}/pboard", "--version"
  end
end
